#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SPEED 1
#define SNAP_TOLERANCE 4
#define TILE_SIZE 14

#define CHAR_PIXEL_OFFSET 1
#define SPRITE_LENGTH 14
#define SPRITE_WIDTH 14

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 160
#define UI_BAR_HEIGHT 6
#define BOX_SIZE 14
#define TILE_WIDTH 14
#define TILE_LENGTH 14
#define NUM_LAYERS 3
#define GRID_COLS (SCREEN_WIDTH / TILE_WIDTH)
#define GRID_ROWS ((SCREEN_HEIGHT - UI_BAR_HEIGHT) / TILE_LENGTH)
#define BROKEN_BLOCK_OFFSET 3

#define GRID_WIDTH (BOX_SIZE * GRID_COLS)
#define GRID_HEIGHT (BOX_SIZE * GRID_ROWS)
#define X_OFFSET ((SCREEN_WIDTH - GRID_WIDTH) / 2)


#define ROW 11
#define COL 9

#define Y_OFFSET (UI_BAR_HEIGHT + BOX_SIZE) 

#endif